Update if.yml

diff --git a/.github/workflows/if.yml b/.github/workflows/if.yml
--- a/.github/workflows/if.yml
+++ b/.github/workflows/if.yml
@@ -28,9 +28,11 @@ jobs:
     # Change status on failure.The step that creates or updates the environment variable does not have access to the new value,
     # but all subsequent steps in a job will have access
      - name: change status to failure 
+       #if: steps.plan.outcome == 'failure'
+       if: env.Job1_status == 'failure'
        #if: fromJSON( ( ${{ env.Job1_status }} == failure || {{ env.Job2_status }}  == failure ) )
        #if: ${{ env.Job1_status }} == failure || {{ env.Job2_status }}  == failure 
-       if: failure() && ${{ env.Job1_status }} == failure || {{ env.Job2_status }}  == failure
+       #if: failure() && ${{ env.Job1_status }} == failure || {{ env.Job2_status }}  == failure
        #if: ${{ env.Job1_status }} == failure
        run: |- 
          echo "status=failure" >> $GITHUB_ENV
